import React, { useState } from 'react';
import { useMutation, useQuery, useQueryClient } from '@tanstack/react-query';
import { monitorRulesApi } from '@/services/api';
import type { MonitorRule, ScanType, SourceType } from '@/types';

export const MonitorRules: React.FC = () => {
  const qc=useQueryClient(); const {data=[]}=useQuery({queryKey:['monitor-rules'],queryFn:monitorRulesApi.list});
  const [form,setForm]=useState({name:'',value:'',source:'github' as SourceType,scan_type:'search_repos' as ScanType,interval_minutes:60 as MonitorRule['interval_minutes']});
  const create=useMutation({mutationFn:monitorRulesApi.create,onSuccess:()=>{qc.invalidateQueries({queryKey:['monitor-rules']});setForm({...form,name:'',value:''});}});
  const remove=useMutation({mutationFn:monitorRulesApi.delete,onSuccess:()=>qc.invalidateQueries({queryKey:['monitor-rules']})});
  return <div className="space-y-6"><h1 className="text-3xl font-bold">Monitor Rules</h1><form className="grid md:grid-cols-6 gap-3 border rounded-lg p-4 bg-card" onSubmit={e=>{e.preventDefault();create.mutate({...form,enabled:true});}}><input className="border rounded px-3 py-2" required placeholder="Rule name" value={form.name} onChange={e=>setForm({...form,name:e.target.value})}/><input className="border rounded px-3 py-2" required placeholder="Target or query" value={form.value} onChange={e=>setForm({...form,value:e.target.value})}/><select value={form.source} onChange={e=>{const source=e.target.value as SourceType;setForm({...form,source,scan_type:source==='you'?'search_repos':'org_repos'});}}><option value="github">GitHub</option><option value="gitlab">GitLab</option><option value="gitee">Gitee</option><option value="you">You.com Search</option></select><select value={form.scan_type} onChange={e=>setForm({...form,scan_type:e.target.value as ScanType})}><option value="search_repos">Search Repositories</option>{form.source==='github'&&<option value="search_code">Search Code</option>}{form.source!=='you'&&<option value="org_repos">Organization Repositories</option>}</select><select value={form.interval_minutes} onChange={e=>setForm({...form,interval_minutes:Number(e.target.value) as MonitorRule['interval_minutes']})}>{[15,30,60,120,360,720,1440].map(v=><option key={v} value={v}>{v} min</option>)}</select><button className="bg-primary text-primary-foreground rounded">Add Rule</button></form><div className="border rounded-lg divide-y bg-card">{data.map(rule=><div key={rule.id} className="p-4 flex justify-between"><div><strong>{rule.name}</strong><p className="text-sm text-muted-foreground">{rule.source} · {rule.value} · {rule.interval_minutes} min · {rule.is_running?'RUNNING':rule.enabled?'ENABLED':'DISABLED'}</p></div><button className="text-destructive" onClick={()=>remove.mutate(rule.id)}>Delete</button></div>)}</div></div>;
};
