# Generated by Django 5.2.8 on 2026-08-27 09:47

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('scans', '0013_scan_source'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterField(
            model_name='monitorrule',
            name='scan_type',
            field=models.CharField(choices=[('org_repos', 'Organization Repositories'), ('org_users', 'Organization Users'), ('search_code', 'Search Code'), ('search_commits', 'Search Commits'), ('search_issues', 'Search Issues'), ('search_repos', 'Search Repositories'), ('search_users', 'Search Users'), ('repository', 'Direct Repository')], max_length=255),
        ),
        migrations.AlterField(
            model_name='scan',
            name='type',
            field=models.CharField(choices=[('org_repos', 'Organization Repositories'), ('org_users', 'Organization Users'), ('search_code', 'Search Code'), ('search_commits', 'Search Commits'), ('search_issues', 'Search Issues'), ('search_repos', 'Search Repositories'), ('search_users', 'Search Users'), ('repository', 'Direct Repository')], default='org_repos', max_length=255),
        ),
        migrations.CreateModel(
            name='RepositoryScanQueue',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('source', models.CharField(choices=[('github', 'GitHub'), ('gitlab', 'GitLab'), ('gitee', 'Gitee'), ('bitbucket', 'Bitbucket'), ('codeberg', 'Codeberg'), ('brave', 'Brave Search')], max_length=32)),
                ('repository_url', models.URLField(max_length=1000)),
                ('owner', models.CharField(max_length=255)),
                ('repository', models.CharField(max_length=255)),
                ('status', models.CharField(choices=[('QUEUED', 'Queued'), ('RUNNING', 'Running'), ('COMPLETED', 'Completed'), ('FAILED', 'Failed')], db_index=True, default='QUEUED', max_length=16)),
                ('error_message', models.TextField(blank=True, default='')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('discovery_scan', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='repository_queue_items', to='scans.scan')),
                ('scan', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='queue_sources', to='scans.scan')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='repository_scan_queue', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at'],
                'constraints': [models.UniqueConstraint(fields=('discovery_scan', 'source', 'repository_url'), name='unique_discovered_repository_per_scan')],
            },
        ),
    ]
