# Generated by Django 5.2.8 on 2026-08-27 09:53

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('scans', '0014_alter_monitorrule_scan_type_alter_scan_type_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='monitorrule',
            name='auto_generated',
            field=models.BooleanField(default=False),
        ),
        migrations.CreateModel(
            name='MonitoringProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('enabled', models.BooleanField(default=True)),
                ('company_name', models.CharField(blank=True, default='', max_length=255)),
                ('domains', models.JSONField(blank=True, default=list)),
                ('email_domains', models.JSONField(blank=True, default=list)),
                ('brands', models.JSONField(blank=True, default=list)),
                ('product_names', models.JSONField(blank=True, default=list)),
                ('internal_projects', models.JSONField(blank=True, default=list)),
                ('internal_domains', models.JSONField(blank=True, default=list)),
                ('github_orgs', models.JSONField(blank=True, default=list)),
                ('gitlab_groups', models.JSONField(blank=True, default=list)),
                ('custom_keywords', models.JSONField(blank=True, default=list)),
                ('interval_minutes', models.PositiveIntegerField(choices=[(15, '15 minutes'), (30, '30 minutes'), (60, '1 hour'), (120, '2 hours'), (360, '6 hours'), (720, '12 hours'), (1440, '24 hours')], default=60)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='monitoring_profiles', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['name'],
            },
        ),
        migrations.AddField(
            model_name='monitorrule',
            name='profile',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='rules', to='scans.monitoringprofile'),
        ),
        migrations.AddConstraint(
            model_name='monitoringprofile',
            constraint=models.UniqueConstraint(fields=('user', 'name'), name='unique_monitoring_profile_name_per_user'),
        ),
    ]
