# Generated by Django 5.2.8 on 2026-08-27 10:48

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('scans', '0015_monitorrule_auto_generated_monitoringprofile_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ExcludedRepository',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('source', models.CharField(choices=[('github', 'GitHub'), ('gitlab', 'GitLab'), ('gitee', 'Gitee'), ('bitbucket', 'Bitbucket'), ('codeberg', 'Codeberg'), ('brave', 'Brave Search')], max_length=32)),
                ('repository_url', models.URLField(max_length=1000)),
                ('normalized_url', models.CharField(db_index=True, max_length=1000)),
                ('owner', models.CharField(blank=True, default='', max_length=255)),
                ('repository', models.CharField(blank=True, default='', max_length=255)),
                ('reason', models.CharField(blank=True, default='', max_length=500)),
                ('enabled', models.BooleanField(db_index=True, default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='excluded_repositories', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['source', 'owner', 'repository'],
            },
        ),
        migrations.CreateModel(
            name='ScanRepository',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('source', models.CharField(choices=[('github', 'GitHub'), ('gitlab', 'GitLab'), ('gitee', 'Gitee'), ('bitbucket', 'Bitbucket'), ('codeberg', 'Codeberg'), ('brave', 'Brave Search')], max_length=32)),
                ('repository_url', models.URLField(max_length=1000)),
                ('normalized_url', models.CharField(db_index=True, max_length=1000)),
                ('owner', models.CharField(blank=True, default='', max_length=255)),
                ('repository', models.CharField(blank=True, default='', max_length=255)),
                ('status', models.CharField(choices=[('DISCOVERED', 'Discovered'), ('EXCLUDED', 'Permanently excluded'), ('SKIPPED_RECENT', 'Recently scanned'), ('QUEUED', 'Queued'), ('SCANNING', 'Scanning'), ('COMPLETED', 'Completed'), ('DEGRADED', 'Partially scanned'), ('FAILED', 'Failed')], db_index=True, default='DISCOVERED', max_length=32)),
                ('error_message', models.TextField(blank=True, default='')),
                ('findings_count', models.PositiveIntegerField(default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('excluded_repository', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='scan_records', to='scans.excludedrepository')),
                ('scan', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='repositories', to='scans.scan')),
            ],
            options={
                'ordering': ['source', 'owner', 'repository'],
            },
        ),
        migrations.AddConstraint(
            model_name='excludedrepository',
            constraint=models.UniqueConstraint(fields=('user', 'source', 'normalized_url'), name='unique_excluded_repository_per_user'),
        ),
        migrations.AddConstraint(
            model_name='scanrepository',
            constraint=models.UniqueConstraint(fields=('scan', 'source', 'normalized_url'), name='unique_repository_per_scan'),
        ),
    ]
