# Generated by Django 5.2.8 on 2026-08-28 01:56

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('scans', '0016_excludedrepository_scanrepository_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='monitoringprofile',
            name='cron_expression',
            field=models.CharField(blank=True, default='', max_length=100),
        ),
        migrations.AddField(
            model_name='monitoringprofile',
            name='schedule_kind',
            field=models.CharField(choices=[('INTERVAL', 'Fixed interval'), ('DAILY', 'Daily'), ('WEEKLY', 'Weekly'), ('CRON', 'Cron expression')], default='INTERVAL', max_length=16),
        ),
        migrations.AddField(
            model_name='monitoringprofile',
            name='schedule_time',
            field=models.TimeField(default=datetime.time(0, 0)),
        ),
        migrations.AddField(
            model_name='monitoringprofile',
            name='schedule_weekdays',
            field=models.JSONField(blank=True, default=list),
        ),
        migrations.AddField(
            model_name='monitorrule',
            name='cron_expression',
            field=models.CharField(blank=True, default='', max_length=100),
        ),
        migrations.AddField(
            model_name='monitorrule',
            name='schedule_kind',
            field=models.CharField(choices=[('INTERVAL', 'Fixed interval'), ('DAILY', 'Daily'), ('WEEKLY', 'Weekly'), ('CRON', 'Cron expression')], default='INTERVAL', max_length=16),
        ),
        migrations.AddField(
            model_name='monitorrule',
            name='schedule_time',
            field=models.TimeField(default=datetime.time(0, 0)),
        ),
        migrations.AddField(
            model_name='monitorrule',
            name='schedule_weekdays',
            field=models.JSONField(blank=True, default=list),
        ),
    ]
