# Generated by Django 5.2.8 on 2026-08-28 02:22

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('scans', '0017_monitoringprofile_cron_expression_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='scan',
            name='monitor_rule',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='scans', to='scans.monitorrule'),
        ),
        migrations.AddField(
            model_name='scan',
            name='trigger_type',
            field=models.CharField(choices=[('MANUAL', 'Manual'), ('SCHEDULED', 'Scheduled'), ('DISCOVERY', 'Discovery'), ('REPOSITORY_QUEUE', 'Repository queue')], db_index=True, default='MANUAL', max_length=32),
        ),
    ]
