# Generated by Django 5.2.8 on 2026-08-28 07:59

from django.db import migrations, models


def disable_brave_rules(apps, schema_editor):
    apps.get_model("scans", "MonitorRule").objects.filter(source="brave").update(enabled=False)


class Migration(migrations.Migration):

    dependencies = [
        ('scans', '0019_monitorrule_timezone'),
    ]

    operations = [
        migrations.RunPython(disable_brave_rules, migrations.RunPython.noop),
        migrations.AlterField(
            model_name='excludedrepository',
            name='source',
            field=models.CharField(choices=[('github', 'GitHub'), ('gitlab', 'GitLab'), ('gitee', 'Gitee'), ('bitbucket', 'Bitbucket'), ('codeberg', 'Codeberg'), ('you', 'You.com Search')], max_length=32),
        ),
        migrations.AlterField(
            model_name='monitorrule',
            name='source',
            field=models.CharField(choices=[('github', 'GitHub'), ('gitlab', 'GitLab'), ('gitee', 'Gitee'), ('bitbucket', 'Bitbucket'), ('codeberg', 'Codeberg'), ('you', 'You.com Search')], default='github', max_length=32),
        ),
        migrations.AlterField(
            model_name='repositoryscanqueue',
            name='source',
            field=models.CharField(choices=[('github', 'GitHub'), ('gitlab', 'GitLab'), ('gitee', 'Gitee'), ('bitbucket', 'Bitbucket'), ('codeberg', 'Codeberg'), ('you', 'You.com Search')], max_length=32),
        ),
        migrations.AlterField(
            model_name='scan',
            name='source',
            field=models.CharField(choices=[('github', 'GitHub'), ('gitlab', 'GitLab'), ('gitee', 'Gitee'), ('bitbucket', 'Bitbucket'), ('codeberg', 'Codeberg'), ('you', 'You.com Search')], default='github', max_length=32),
        ),
        migrations.AlterField(
            model_name='scanrepository',
            name='source',
            field=models.CharField(choices=[('github', 'GitHub'), ('gitlab', 'GitLab'), ('gitee', 'Gitee'), ('bitbucket', 'Bitbucket'), ('codeberg', 'Codeberg'), ('you', 'You.com Search')], max_length=32),
        ),
    ]
