# Generated by Django 5.2.8 on 2026-08-27 09:55

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0008_detectionpattern'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='CodeFingerprint',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('kind', models.CharField(choices=[('BASELINE', 'Internal baseline'), ('CANDIDATE', 'Discovered candidate')], default='BASELINE', max_length=16)),
                ('source_repository', models.URLField(blank=True, default='', max_length=1000)),
                ('file_path', models.CharField(blank=True, default='', max_length=1000)),
                ('content_sha256', models.CharField(db_index=True, max_length=64)),
                ('token_count', models.PositiveIntegerField(default=0)),
                ('simhash', models.CharField(max_length=16)),
                ('minhash', models.JSONField(default=list)),
                ('tlsh', models.CharField(blank=True, default='', max_length=255)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='code_fingerprints', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='SimilarityMatch',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('simhash_score', models.FloatField()),
                ('minhash_score', models.FloatField()),
                ('combined_score', models.FloatField(db_index=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('baseline', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='baseline_matches', to='core.codefingerprint')),
                ('candidate', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='candidate_matches', to='core.codefingerprint')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='similarity_matches', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-combined_score'],
                'constraints': [models.UniqueConstraint(fields=('baseline', 'candidate'), name='unique_code_similarity_pair')],
            },
        ),
    ]
