# Generated by Django 5.2.8 on 2026-08-27 09:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('integrations', '0005_userintegration_error_message_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userintegration',
            name='provider',
            field=models.CharField(choices=[('github', 'GitHub'), ('gitlab', 'GitLab'), ('slack', 'Slack')], max_length=255),
        ),
    ]
