# Generated by Django 5.2.8 on 2026-08-27 09:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('integrations', '0006_alter_userintegration_provider'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userintegration',
            name='provider',
            field=models.CharField(choices=[('github', 'GitHub'), ('gitlab', 'GitLab'), ('gitee', 'Gitee'), ('slack', 'Slack')], max_length=255),
        ),
    ]
