# Generated by Django 5.2.8 on 2026-08-28 03:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('integrations', '0008_alter_userintegration_provider'),
    ]

    operations = [
        migrations.AddField(
            model_name='userintegration',
            name='proxy_url_encrypted',
            field=models.TextField(blank=True, default=''),
        ),
    ]
