# Generated by Django 5.2.8 on 2026-08-28 07:59

from django.db import migrations, models


def remove_brave_integrations(apps, schema_editor):
    apps.get_model("integrations", "UserIntegration").objects.filter(provider="brave").delete()


class Migration(migrations.Migration):

    dependencies = [
        ('integrations', '0009_userintegration_proxy_url_encrypted'),
    ]

    operations = [
        migrations.RunPython(remove_brave_integrations, migrations.RunPython.noop),
        migrations.AlterField(
            model_name='userintegration',
            name='provider',
            field=models.CharField(choices=[('github', 'GitHub'), ('gitlab', 'GitLab'), ('gitee', 'Gitee'), ('you', 'You.com Search'), ('slack', 'Slack')], max_length=255),
        ),
    ]
